name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:

env:
  PIP_CACHE_DIR: ${{ github.workspace }}\pipcache

jobs:
  build_windows:
    runs-on: windows-2022
    steps:
      - name: check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: download pip cache
        uses: actions/cache@v3
        with:
          key: pipcache-run-${{ github.run_number}}
          restore-keys: pipcache-run-
          path: ${{ env.PIP_CACHE_DIR }}
      - name: set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: build and install
        working-directory: ${{ github.workspace }}
        run: |
          pip install setuptools wheel
          python setup.py sdist bdist_wheel
          pip install $(Get-ChildItem dist\delvewheel-*.whl)
          if ((git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | Out-String).Contains("delvewheel/_version.py`r`n")) {
            echo VERSION_CHANGED=1 | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          }
      - name: upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: delvewheel
          path: ${{ github.workspace }}\dist\*
      - name: run tests with Python 3.10
        working-directory: ${{ github.workspace }}\tests
        run: python run_tests.py -v
      - name: set up Python 3.6
        uses: actions/setup-python@v4
        with:
          python-version: '3.6'
      - name: run tests with Python 3.6
        working-directory: ${{ github.workspace }}\tests
        run: |
          pip install wheel
          pip install $(Get-ChildItem ..\dist\delvewheel-*.whl)
          python run_tests.py -v Python36TestCase
      - name: set up PyPy3.9
        uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
      - name: run tests with PyPy3.9
        working-directory: ${{ github.workspace }}\tests
        run: |
          pip install wheel
          pip install $(Get-ChildItem ..\dist\delvewheel-*.whl)
          python run_tests.py -v PyPyTestCase
      - name: set up Ubuntu 22.04
        uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-22.04
          additional-packages: python-is-python3 python3-pip python3-wheel
      - name: run tests on Ubuntu 22.04
        working-directory: ${{ github.workspace }}\tests
        shell: wsl-bash {0}
        run: |
          export PIP_CACHE_DIR=$(wslpath '${{ env.PIP_CACHE_DIR }}')
          pip install ../dist/delvewheel-*.whl
          python run_tests.py -v LinuxTestCase
      - name: deploy
        if: env.VERSION_CHANGED == '1' && github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository_owner == 'adang1345'
        working-directory: ${{ github.workspace }}
        run: |
          pip install twine
          twine upload --skip-existing -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist\*
